#!/bin/sh
set -e

mkdir -p /etc/lidar-service
if [ ! -f /etc/lidar-service/config.yaml ]; then
  cp /opt/lidar-service/config/config.yaml /etc/lidar-service/config.yaml
fi

if [ ! -d /opt/lidar-service/venv ]; then
  python3 -m venv /opt/lidar-service/venv
  /opt/lidar-service/venv/bin/pip install --upgrade pip
  /opt/lidar-service/venv/bin/pip install --no-index --find-links=/opt/lidar-service/wheels /opt/lidar-service/app
fi

systemctl daemon-reexec
systemctl daemon-reload
systemctl enable lidar-service
systemctl restart lidar-service
